### DataFrame 만들기

In [3]:
import pandas as pd

students = pd.DataFrame({
    'name':    ['김민준', '이서현', '박지우', '최하은', '정도윤'],
    'age':     [22, 23, 22, 24, 23],
    'math':    [85, 92, 78, 95, 88],
    'english': [76, 88, 91, 70, 85],
    'grade':   ['B', 'A', 'B', 'A', 'A']
})

### 기본 탐색

In [4]:
# head(행개수) : default 5
students.head()

  name  age  math  english grade
0  김민준   22    85       76     B
1  이서현   23    92       88     A
2  박지우   22    78       91     B
3  최하은   24    95       70     A
4  정도윤   23    88       85     A

In [7]:
# shape : (행, 열) 튜플로 반환
students.shape

(5, 5)

In [ ]:
# dtype : 컬럼별 타입 확인
students.dtypes

name         str
age        int64
math       int64
english    int64
grade        str
dtype: object

In [ ]:
# info() : 타입 + 결측치 수
# RangeIndex: 행수, Data columns(컬럼수), dtypes: 컬럼 데이터 타입, memory usage : 용량
# Non-Null Count : 결측치 개수
students.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   name     5 non-null      str
 1   age      5 non-null      int64
 2   math     5 non-null      int64
 3   english  5 non-null      int64
 4   grade    5 non-null      str
dtypes: int64(3), str(2)
memory usage: 332.0 bytes

In [10]:
# describe() : 숫자형 통계
students.describe()

            age       math    english
count   5.00000   5.000000   5.000000
mean   22.80000  87.600000  82.000000
std     0.83666   6.580274   8.746428
min    22.00000  78.000000  70.000000
25%    22.00000  85.000000  76.000000
50%    23.00000  88.000000  85.000000
75%    23.00000  92.000000  88.000000
max    24.00000  95.000000  91.000000

### 컬럼 선택

In [21]:
print(students['name']), print(type(students['name']))
print("*" * 40)
print(students[['name','math']]), print(type(students[['name', 'math']]))

0    김민준
1    이서현
2    박지우
3    최하은
4    정도윤
Name: name, dtype: str
<class 'pandas.Series'>
****************************************
  name  math
0  김민준    85
1  이서현    92
2  박지우    78
3  최하은    95
4  정도윤    88
<class 'pandas.DataFrame'>

(None, None)